server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?serverTimezone=Asia/Shanghai
    username: root
    password: admin
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  main:
    banner-mode: off
